name: airbnb_dbt

profile: Airbnb_DBT

# seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

# seeds:
#   # Builds seeds into '<your_schema_name>_raw'
#   airbnb_dbt:
#     +schema: raw

models:
  airbnb_dbt:
    +static_analysis: strict # Enforce strict static analysis on all models in this project
    # Materialize bronze models as views, and marts as tables
    bronze:
      +materialized: view
      +schema: bronze
    marts:
      +materialized: table
      +schema: silver
